### ISSUE TITLE
Arduino doesn't have permission to write to ~/.beansketches/bean/

### ISSUE THREAD

**Issue by jcnesci** [PunchThrough/bean-arduino-core#27]
After installing Bean CLI, I'm wondering why I get this error when pressing Upload button in Arduino.

```
Arduino: 1.6.12 (Mac OS X), TD: 1.36, Board: "LightBlue Bean (2.0.3)"

Sketch uses 5,822 bytes (18%) of program storage space. Maximum is 32,256 bytes.
Global variables use 670 bytes of dynamic memory.
Traceback (most recent call last):
  File "/Applications/Arduino.app/Contents/Java/hardware/tools/bean/post_compile", line 94, in <module>
    copy_hex(parsed_args)
  File "/Applications/Arduino.app/Contents/Java/hardware/tools/bean/post_compile", line 89, in copy_hex
    shutil.copyfile(tmp_compiled_path, perm_compiled_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Users/jc/.beansketches/bean/lightblue-bean-test-2-photores.hex'
IOError: [Errno 13] Permission denied: '/Users/jc/.beansketches/bean/lightblue-bean-test-2-photores.hex'
```

Is there a way to increase permissions of these scripts triggered from inside Arduino app so they can write the files?

**Comment by estiens** [comment]
Also having this problem

**Comment by estiens** [comment]
.beansketches is prob owned by root, you can get around with by doing a `sudo chown`
